name: Generate EPG

on:
  schedule:
    - cron: '0 0 * * *'  # A cada dia à meia-noite, ajuste conforme necessário
  workflow_dispatch:

jobs:
  generate_epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python script_generate_epg.py

      - name: Upload EPG file
        uses: actions/upload-artifact@v2
        with:
          name: epg-file
          path: PiauiTV.m3u.epg.xml
